# Generated by Django 4.1 on 2025-03-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.CharField(max_length=4096, verbose_name='текст контента')),
                ('is_main_group', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контенты',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('template_fields', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('is_admin', models.BooleanField(default=False)),
                ('has_plan', models.BooleanField(default=False)),
                ('chat_history', models.JSONField(blank=True, default=dict, null=True, verbose_name='История переписки пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserTemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='Отображаемое название')),
                ('template_field', models.CharField(max_length=50, verbose_name='Поле в шаблоне')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_variables', to='bot.user')),
            ],
            options={
                'verbose_name': 'Переменная шаблона',
                'verbose_name_plural': 'Переменные шаблона',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Файл документа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла')),
                ('file_type', models.CharField(max_length=50, verbose_name='Тип файла')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bot.documents')),
            ],
            options={
                'verbose_name': 'Файл документа',
                'verbose_name_plural': 'Файлы документов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('button_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20, verbose_name='текст кнопки')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Child_content', to='bot.content')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent_content', to='bot.content')),
            ],
            options={
                'verbose_name': 'кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
    ]
