# Generated by Django 4.1 on 2025-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('button_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='имя кнопки а также колбэк дата')),
                ('button_group', models.CharField(max_length=20, verbose_name='имя группы кнопок')),
                ('button_text', models.CharField(max_length=100, verbose_name='текст кнопки')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
        migrations.CreateModel(
            name='ButtonGroup',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Имя группы кнопок')),
                ('parent_button', models.CharField(max_length=20, verbose_name='Имя родительской кнопки')),
                ('is_main_group', models.BooleanField(default=False)),
                ('is_document', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Группа кнопок',
                'verbose_name_plural': 'Группы кнопок',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('address', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('parent_button', models.CharField(max_length=20, verbose_name='Имя родительской кнопки')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='ParsValues',
            fields=[
                ('world_value', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Переменная в ворлде')),
                ('user_text', models.CharField(max_length=20, verbose_name='текст который видит пользователь')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('name_txt', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Имя текста')),
                ('txt_text', models.CharField(max_length=4000, verbose_name='Текст кнопок')),
                ('parent_button', models.CharField(max_length=20, verbose_name='имя родительской кнопки')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('is_admin', models.BooleanField(default=False)),
                ('has_plan', models.BooleanField(default=False)),
                ('message_context', models.JSONField(blank=True, null=True, verbose_name='История переписки пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
