# Generated by Django 4.1 on 2025-06-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_main_group',
        ),
        migrations.AlterField(
            model_name='button',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent_content', to='bot.content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_text',
            field=models.TextField(verbose_name='текст контента'),
        ),
    ]
