# Generated by Django 4.1 on 2025-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_content_is_main_group_alter_button_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='button_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
